version: '3.9'
services:
  my-api:
    image: compliment-generator-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"